// Code generated by "generate_version.sh"; DO NOT EDIT.
// Generated on: 2025-07-16

package main

const (
	Name        = "fad"
	Project     = "go install github.com/markdingo/fad@latest"
	ReleaseDate = "2025-07-16"
	Version     = "1.0.0"
)

// Code generated by "generate_version.sh"; DO NOT EDIT.
